packages:
  - '.'
  - templates/*
  - templates/unplugin/playground
ignoreWorkspaceRootCheck: true
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  oxc-resolver: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/*'
  - '@pnpm/*'
  - execa
  - mdat-plugin-cli-help
  - rolldown-plugin-dts
  - tsdown
  - vite
  - bumpp@12.2.0
  - mdat@3.1.0
  - remark-mdat@3.0.1
  - taze@20.0.0
