# Required by @kitschpatrol/shared-config

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - puppeteer
  - unrs-resolver
  - unrs-resolver

overrides:
  'vite': 'npm:rolldown-vite@7.3.0'

publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
